repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        name: Gitleaks - поиск секретов
        entry: gitleaks protect --verbose --redact --staged
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        name: Проверка больших файлов
        args: ['--maxkb=1000']
      - id: check-merge-conflict
        name: Проверка merge-конфликтов
      - id: end-of-file-fixer
        name: Пустая строка в конце файла
      - id: trailing-whitespace
        name: Пробелы в конце строк
